---
title: "class 05"
author: "Henry Chen"
date: "2026-09-09"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
    theme: simplex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Game 01: Subsetting Lists
```{r game01}

campus = jsonlite::fromJSON(
  "https://isa401-find-your-seat.vercel.app/campus.json")

names(campus) # shows the named elements within a list(or vector) or the cols in a data frame

fsb = campus$Farmer # saving the named farmer list in FSB
# equivalent campus [['Farmer]] by name or campus[[5]] by position
fsb$code

fsb[[8]]$`2`$sections # fsb$floors

sec_floor = fsb[[8]]$`2`

sec_floor_rooms = sec_floor[[3]]
sec_floor_rooms[6, 2]
sec_floor_rooms[6, 'isa_sections']

```



## Reading the Excel

```{r occupations}
occupations = readxl::read_excel(
  path = "../data/occupation.xlsx",
  sheet = 5,
  skip = 1
)

# - when you subset in R drops these specific things
# given that they are three, I put them in a vector
# notice the "," after the parentheses
# nothing  after the comma which means all columns

occupations = occupations[-c(32,33,34), ]
# alternatively
occupations = occupations[1:31, ]

```


## Read the JSON file
```{r read_json}
json_url = ("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json?$limit=100")
crashes_json = jsonlite::fromJSON(json_url)
dplyr::glimpse(crashes_json)

```


## Reading the CSV file
```{r read_csv}
logins = readr::read_csv("https://isa401-import-heist.vercel.app/api/stage1?seat=R2-1&s=B")
log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=smithj31")

events_df = log$events

jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/finish?code=NUMBER&seat=R2-1&s=B")




```